DaxiangLi: add checking to foo.py
HuanianLi/kaiba pull request #2
Opened 2018-07-26 03:57 UTC by DaxiangLi

HuanianLi: I added checking to foo.py, please review, thanks.

2018-07-26 04:49 UTC, HuanianLi requested changes

2018-07-26 04:49 UTC, HuanianLi commented on foo.py
> +        return 1
Please use 'return -1' instead at L8.

2018-07-26 05:01 UTC, DaxiangLi commented on foo.py
> +        return 1
Done. Please check again.

2018-07-26 05:20 UTC, HuanianLi requested changes
Hi Daxiang! If you get to the final version of the pull, can you please squash the commits into a single one and let me know so I can check it?

2018-07-26 05:48 UTC, DaxiangLi commented
The two commits are squashed into a single one now, please check again.

2018-07-26 07:35 UTC, merged

2018-07-27 06:37 UTC, DaxiangLi commented
HuanianLi, I have resolved the conflict in foo.py, please review and merge the code, thanks.